version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: chat
      MYSQL_USER: chat
      MYSQL_PASSWORD: chat
      MYSQL_ROOT_PASSWORD: root_password # MySQL의 root 비밀번호를 지정합니다.
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql # MySQL 데이터 디렉토리를 호스트의 ./mysql-data 경로와 연결합니다.
#  zookeeper:
#    image: confluentinc/cp-zookeeper:6.2.0
#    container_name: zookeeper
#    ports:
#      - 2181:2181
#    environment:
#      - ZOOKEEPER_CLIENT_PORT=2181
#  kafka:
#    image: confluentinc/cp-kafka:6.2.0
#    container_name: kafka
#    ports:
#      - 9092:9092
#    depends_on:
#      - zookeeper
#    environment:
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
#      - KAFKA_CREATE_TOPICS=Topic:1:1
#    volumes:
#      - ./kafka-data:/var/lib/kafka/data
#  rabbitmq:
#    image: rabbitmq:3.9.7
#    container_name: rabbitmq
#    ports:
#      - 5672:5672
#      - 15672:15672
#      - 61613:61613
#

#
#  app:
#    image: ankyeongeun/chat-and-pay:chat
#    container_name: app
#    ports:
#      - 8080:8080
#    depends_on:
#      - postgres
#    volumes:
#      - ./logs:/app/logs
