version: "3.6"
services:
  client-app-1:
    image: ankyeongeun/chat-and-pay:chat4
    container_name: client-app
    ports:
      - "8080:8080"
    networks:
      - localnet

  client-app-2:
    image: ankyeongeun/chat-and-pay:chat4
    container_name: client-app
    ports:
      - "8081:8081"
    networks:
      - localnet

  client-app-3:
    image: ankyeongeun/chat-and-pay:chat4
    container_name: client-app
    ports:
      - "8082:8082"
    networks:
      - localnet

networks:
  localnet:
    attachable: true